# This workflow builds the Node.js frontend and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testing Frontend

on:
  pull_request:
    branches: [ "main" ]
    paths: 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env containing secrets.
        env:
          API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REF_URL: ${{ secrets.REACT_APP_FIREBASE_REF_URL }}
        run: |
          cat <<EOF > .env
          REACT_APP_FIREBASE_API_KEY="$API_KEY"
          REACT_APP_FIREBASE_AUTH_DOMAIN="$AUTH_DOMAIN"
          REACT_APP_FIREBASE_PROJECT_ID="$PROJECT_ID"
          REACT_APP_FIREBASE_REF_URL="$REF_URL"
          EOF
        working-directory: ./frontend
      - run: npm ci
        working-directory: ./frontend
      - run: npm run build --if-present
        working-directory: ./frontend
      # transformIngorePatterns flag added to fix Jest-Axios error. Source: https://github.com/axios/axios/issues/5101
      - run: npm test -- --transformIgnorePatterns "node_modules/(\?\!axios)/"
        working-directory: ./frontend
