# This workflow builds the Node.js frontend and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testing Frontend

on:
  pull_request:
    paths: 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./frontend
      - run: npm run build --if-present
        working-directory: ./frontend
      # transformIngorePatterns flag added to fix Jest-Axios error. Source: https://github.com/axios/axios/issues/5101
      - run: npm test -- --transformIgnorePatterns "node_modules/(\?\!axios)/"
        working-directory: ./frontend
