# This workflow builds the Node.js frontend and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testing Frontend

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/testing_frontend.yml'
      - '.github/actions/frontend-setup/action.yml'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/frontend-setup
        with:
          shell: bash
          node-version: ${{ matrix.node-version }}
          API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }},
          AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }},
          PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }},
          REF_URL: ${{ secrets.REACT_APP_FIREBASE_REF_URL }}
      - name: Run front-end tests.
      # transformIgnorePatterns flag added to fix Jest-Axios error. Source: https://github.com/axios/axios/issues/5101
        run: npm test -- --transformIgnorePatterns "node_modules/(\?\!axios)/"
        working-directory: ./frontend
